spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://ep-patient-union-a6wqabnv-pooler.us-west-2.aws.neon.tech/sioverflow?sslmode=require
    username: sioverflow_owner
    password: npg_8Wh0InVJSqpO
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 6e5198be8d608765738cf714efcc2c4c7f25947a07ee831e7756b6cf0f2f2b98
github:
  host: "https://github.com"
  api-host: "https://api.github.com"
  client-id: Ov23liA2Hr0kEPO2EaZ8
  client-secret: 28911a7eabc49d0b2bfe3d8c16ea60e0c65faccc
  scope: user:email
  redirect-uri: http://localhost:5173/login/github/code