spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://host:5432/sioverflow
    username: username
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true

logging:
  level:
    '[com.srivatsan177.sioverflow]': DEBUG

github:
  host: "https://github.com"
  api-host: "https://api.github.com"
  client-id: github_client_id
  client-secret: github_client_secret
  scope: user:email
  redirect-uri: http://localhost:5173/login/github/code