services:
  db:
    image: postgres:17-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sioverflow
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data